#!/usr/bin/python

"""
Fixes verilog code generated by the netlister.
  1. Changes Vcc/GND from wires into supply1/supply0 respectively
  2. Suppresses identical input declarations for modules
"""

import sys
import StringIO


def main(args):
    if len(args) != 1:
        print "USAGE: %s module.v" % sys.argv[0]
        print "Fixes netlisted verilog code"
        return 2
    filename = args[0]
    out_stream = StringIO.StringIO()
    with open(filename) as in_stream:
        fixup(in_stream, out_stream)
    out_stream.seek(0)
    with open(filename, "w") as new_stream:
        map(new_stream.write, out_stream)


def fixup(in_stream, out_stream):
    wireset = []
    checking_wires = False
    for line in in_stream:
        line = line.replace("wire GND ;", "supply0 GND ;")
        line = line.replace("wire Vcc ;", "supply1 Vcc ;")
        wire = line.strip(",\n")
        if checking_wires and wire in wireset:
            continue
        if line.endswith(" ( \n"):
            out_stream.write(line)
            checking_wires = True
        elif line.endswith(");\n"):
            if checking_wires:
                out_stream.write(",\n".join(wireset) + "\n")
                checking_wires = False
                wireset = []
            out_stream.write(line)
        elif checking_wires:
            wireset.append(wire)
        else:
            out_stream.write(line)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
